name: velocitynet
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.2
  flutter_phosphor_icons: ^0.0.1+6
  flutter_screenutil: ^5.9.3
  smooth_scroll_multiplatform: ^1.0.8
  blur: ^4.0.0
  google_fonts: ^6.2.1
  simple_gradient_text: ^1.3.0
  flutter_svg: ^2.0.17
  visibility_detector: ^0.4.0+2
  flutter_flip_card: ^0.0.6
  provider: ^6.1.2
  flutter_speedtest: ^0.2.0
  flutter_internet_speed_test: ^1.5.0
  geolocator: ^12.0.0
  http: ^1.3.0
  file_picker: ^5.3.3
  syncfusion_flutter_pdfviewer: ^23.1.39
  dropdown_button2: ^2.3.9
  contained_tab_bar_view_with_custom_page_navigator: ^0.1.3
  url_launcher: ^6.3.1
  phosphor_flutter: ^2.1.0
  
  


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true
  assets:
  - lib/assets/
  - lib/assets/images/
  - lib/assets/images/globoplay/
  - lib/assets/images/telecine/
  - lib/assets/images/premiere/
  - lib/assets/images/max/
  - lib/assets/images/deezer/
  - lib/assets/images/tv_plans/
  - lib/assets/images/topHD/
  - lib/assets/images/startHD/
  - lib/assets/images/premiumHD/
  
  fonts:
    - family: EutoStile
      fonts:
        - asset: lib/assets/fonts/eurostile-next-lt-pro-semibold.otf
          weight: 700
        - asset: lib/assets/fonts/eurostile-next-lt-pro-light.otf
          weight: 200
          
    - family: PetrovSans
      fonts:
        - asset: lib/assets/fonts/petrov/PetrovSans-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/petrov/PetrovSans-Regular.ttf
          weight: 200         
        - asset: lib\assets\fonts\CalSans-Regular.ttf
          weight: 200

      
        

 